# -*- coding: utf-8 -*-
"""Extract Frames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XHf2ZPzu6EmQF9sBxBwg0l5Wrt_JHCa1
"""

#라이브러리 호출
import cv2
import os

filepath = '/content/drive/MyDrive/Flask/static/user_360/user.mp4'
video = cv2.VideoCapture(filepath) #'' 사이에 사용할 비디오 파일의 경로 및 이름을 넣어주도록 함

if not video.isOpened():
    print("Could not Open :", filepath)
    exit(0)

length = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = video.get(cv2.CAP_PROP_FPS)

#프레임을 저장할 디렉토리를 생성
try:
    if not os.path.exists(filepath[:-4]):
        os.makedirs(filepath[:-4])
except OSError:
    print ('Error: Creating directory. ' +  filepath[:-4])


if video.isOpened():
    count = 0
    while True:
        ret, image = video.read()
        if(int(video.get(1000)) % fps == 0): #앞서 불러온 fps 값을 사용하여 1초마다 추출
            cv2.imwrite(filepath[:-4]+ "/%05d.jpg" % count, image)
            print('Saved frame number :', str(int(video.get(1))))
            count += 1

    video.release()