# -*- coding: utf-8 -*-
"""main2_res.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQsUvPplF9AcIBvYXpCg0A6qkqfpzl3E
"""

# # This is a specific model name, and it will be used if you do not change it. This is the case of `trump`
# model_id = "afan_6=ns=2"
model_id = "model"

# # the source input information, here \" is escape character of double duote "
# src_path = "\"path?=/content/iPERCore/assets/samples/sources/afan_6/afan_6=ns=2," \
#              "name?=afan_6=ns=2," \
#              "bg_path?=/content/iPERCore/assets/samples/sources/afan_6/IMG_7217.JPG\""
src_path = "\"path?=/content/drive/MyDrive/Flask/static/user_360/user," \
             "bg_path?=/content/drive/MyDrive/Flask/static/background/bg.jpg\""

# # the reference input information. There are three reference videos in this case.
# # here \" is escape character of double duote "
# ref_path = "\"path?=/content/iPERCore/assets/samples/references/akGexYZug2Q_2.mp4.mp4," \
#              "name?=akGexYZug2Q_2," \
#              "pose_fc?=300\""
ref_path = "\"path?=/content/drive/MyDrive/Flask/static/dance/BTS Dynamite_user.mp4," \
             "pose_fc?=300\""


!python -m iPERCore.services.run_imitator  \
  --gpu_ids     $gpu_ids       \
  --num_source  $num_source    \
  --image_size  $image_size    \
  --output_dir  $output_dir    \
  --model_id    $model_id      \
  --cfg_path    $cfg_path      \
  --src_path    $src_path      \
  --ref_path    $ref_path