# -*- coding: utf-8 -*-
"""main2_res.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oQsUvPplF9AcIBvYXpCg0A6qkqfpzl3E
"""

# mp4 = open("./results/primitives/afan_6=ns=2/synthesis/imitations/afan_6=ns=2-akGexYZug2Q_2.mp4", "rb").read()
mp4 = open("./results/primitives/synthesis/imitations/-BTS Dynamite_user.mp4.mp4", "rb").read()

data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML(f"""
<video width="100%" height="100%" controls>
      <source src="{data_url}" type="video/mp4">
</video>""")